<?php

use Illuminate\Database\Seeder;
use Azizner\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    private $cityNames = [
        'Agarak',
        'Ahnidzor',
        'Akhtala',
        'Akhtala aroghjaranin kits',
        'Akner',
        'Akori',
        'Alaverdi',
        'Amoj',
        'Amrakits',
        'Antaramut',
        'Antarashen',
        'Apaven',
        'Ardvi',
        'Arevashogh',
        'Arevatsag',
        'Arjut',
        'Arjut kayaranin kits',
        'Armanis',
        'Artsni',
        'Atan',
        'Aygehat',
        'Aznvadzor',
        'Bazum',
        'Bendik',
        'Blagodarnoye',
        'Bovadzor',
        'Chkalov',
        'Chochkan',
        'Darpas',
        'Dashtadem',
        'Debet',
        'Dsegh',
        'Dzoraget',
        'Dzoragyugh',
        'Dzoramut',
        'Dzyunashogh',
        'Fioletovo',
        'Gargar',
        'Geghasar',
        'Getavan',
        'Ghursali',
        'Gogaran',
        'Gogavan Privolnoye',
        'Gugark',
        'Gyulagarak',
        'Haghpat',
        'Hagvi',
        'Halavar',
        'Hartagyugh',
        'Haydarli',
        'Hobardzi',
        'Hovnanadzor',
        'Jiliza',
        'Jrashen',
        'Kachachkut',
        'Karaberd',
        'Karadzor',
        'Karinj',
        'Karkop',
        'Karmir Aghek',
        'Katnaghbyur',
        'Katnajur',
        'Katnarat',
        'Khnkoyan',
        'Kilisa',
        'Kober kayaran',
        'Koghes',
        'Kruglaya Shishka',
        'Kurtan',
        'Lejan',
        'Lermontovo',
        'Lernahovit',
        'Lernantsk',
        'Lernapat',
        'Lernavan',
        'Lori Berd',
        'Lorut',
        'Lusaghbyur',
        'Margahovit',
        'Marts',
        'Medovka',
        'Meghvahovit',
        'Mets Ayrum',
        'Mets Parni',
        'Metsavan',
        'Mghart',
        'Mikhayelovka',
        'Neghots',
        'Nor Khachakap',
        'Noramut',
        'Norashen',
        'Novoseltsovo',
        'Odzun',
        'Paghaghbyur',
        'Pambak',
        'Pambak kayaranin kits',
        'Petrovka',
        'Pokr Ayrum',
        'Pushkino',
        'Sarahart',
        'Saralanj',
        'Saramej',
        'Saratovka',
        'Sarchapet',
        'Shahumyan',
        'Shamlugh',
        'Shamut',
        'Shenavan',
        'Shirakamut',
        'Shnogh',
        'Spitak',
        'Stepanavan',
        'Sverdlov',
        'Tashir',
        'Teghut',
        'Tsaghkaber',
        'Tsaghkashat',
        'Tsater',
        'Tumanyan',
        'Urasar',
        'Urut',
        'Vahagnadzor',
        'Vahagni',
        'Vanadzor',
        'Vardablur',
        'Verin Akhtala',
        'Yaghdan',
        'Yeghegnut',

    ];

    public function run()
    {
        foreach ($this->cityNames as $cityName)
            City::create(
                [
                    'name' => $cityName,
                    'region_id' => 1,
                ]
            );
    }



}
